# -*- coding: utf-8 -*-
"""Balanceo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecwcUgtBlvyzxLD2nmLlTDwWjaffrTkP
"""

def balanceoV(e):
    p = []
    pares = {')': '(', ']': '[', '}': '{'}
    pasos = []

    for i, caracter in enumerate(e):
        if caracter in pares.values():
            p.append((caracter, i))
            pasos.append(f"Push: '{caracter}' en posición {i} -> Pila: {[x[0] for x in p]}")
        elif caracter in pares:
            if not p:
                pasos.append(f"Error: '{caracter}' en posición {i}")
                return False, pasos
            ua, pos = p.pop()
            pasos.append(f"Pop: '{ua}' (posición {pos}) al encontrar '{caracter}' en posición {i}")
            if ua != pares[caracter]:
                pasos.append(
                    f"Error: '{caracter}' en posición {i} no coincide con '{ua}' en posición {pos}")
                return False, pasos

    if p:
        pasos.append(f"Error: Símbolos sin cerrar: {[x[0] for x in p]}")
        return False, pasos

    pasos.append("Esta correctamente balanceado\n")
    return True, pasos


def leer_archivo(nombre_archivo):
    try:
        with open(nombre_archivo, 'r') as archivo:
            for num_linea, linea in enumerate(archivo, 1):
                linea = linea.strip()
                if not linea:
                    continue

                balanceada, pasos = balanceoV(linea)

                for paso in pasos:
                    print(paso)

                print(f"Resultado: {'BALANCEADA' if balanceada else 'NO BALANCEADA'}\n")

    except FileNotFoundError:
        print("Error")


if __name__ == "__main__":
    nombre_archivo = input("Ingrese el nombre del archivo: ")
    leer_archivo(nombre_archivo)